name: Python package

on:
  push:
    tags:
      - '*'

jobs:
  build_linux_wheels:
    name: Build wheels on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build --wheel
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: output-wheels-linux-latest
          path: ./dist/*.whl

  build_windows_wheels:
    name: Build wheels on windows-latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build package
        uses: pypa/cibuildwheel@v2.16.5
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: output-wheels-windows-latest
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: output-sdist
          path: dist/*.tar.gz

  publish-to-pypi:
    needs: [build_linux_wheels, build_windows_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          pattern: output-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
